
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 31 19:32:27 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 21;
  public static final int READ = 14;
  public static final int IDENT = 26;
  public static final int PLUS = 17;
  public static final int RBRACE = 4;
  public static final int RPAREN = 13;
  public static final int DIGIT = 25;
  public static final int EQUAL = 10;
  public static final int SEMI = 6;
  public static final int RETURN = 24;
  public static final int MINUSMINUS = 15;
  public static final int TRUE = 28;
  public static final int LBRACKET = 8;
  public static final int LPAREN = 12;
  public static final int LBRACE = 3;
  public static final int RBRACKET = 9;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int PROG = 2;
  public static final int FALSE = 29;
  public static final int MINUS = 18;
  public static final int PLUSPLUS = 16;
  public static final int PRINT = 23;
  public static final int CONST = 5;
  public static final int error = 1;
  public static final int NEW = 22;
  public static final int NULL = 30;
  public static final int MUL = 19;
  public static final int VOID = 11;
  public static final int CHAR_CONST = 27;
}

